/*
 * This file is part of the HyperGraphDB source distribution. This is copyrighted
 * software. For permitted uses, licensing options and redistribution, please see
 * the LicensingInformation file at the root level of the distribution.
 *
 * Copyright (c) 2007
 * Kobrix Software, Inc.  All rights reserved.
 */
package org.hypergraphdb.app.xsd;

import java.util.HashMap;
import java.util.Map;

import org.hypergraphdb.HGException;
import org.hypergraphdb.HGHandle;
import org.hypergraphdb.HGHandleFactory;
import org.hypergraphdb.HGPersistentHandle;
import org.hypergraphdb.HyperGraph;
import org.hypergraphdb.LazyRef;
import org.hypergraphdb.atom.HGAtomRef;
import org.hypergraphdb.type.AtomRefType;
import org.hypergraphdb.type.HGAtomType;
import org.hypergraphdb.type.LinkRecord;
import org.hypergraphdb.type.Record;
import org.hypergraphdb.type.Slot;
import org.hypergraphdb.type.TypeUtils;

/**
 * This will be actually generated by CTC.
 */
public class USAddressComplexRecordType implements HGAtomType
{
   private HyperGraph hg;

   /**
    * 
    */
   public Object make(
      HGPersistentHandle handle, LazyRef<HGHandle[]> targetSet,
      LazyRef<HGHandle[]> incidenceSet)
   {
      Map result = new HashMap<String,Object>();

      HGPersistentHandle[] layout = hg.getStore().getLink(handle);

      for (int i = 0; i < layout.length/3; i++)
      {
         HGAtomType type=hg.getTypeSystem().getType(layout[3 * i]);

         Object key = TypeUtils.makeValue(hg, layout[3 * i + 1], type);
         Object value = TypeUtils.makeValue(hg, layout[3 * i + 2], type);
         
         result.put(key, value);
      }

      return result;
   }

   public void release(
      HGPersistentHandle handle)
   {
      // TODO Auto-generated method stub
   }

   /**
    * 
    */
   public void setHyperGraph(
      HyperGraph hg)
   {
      this.hg = hg;
   }

   /**
    * 
    */
   public HGPersistentHandle store(
      Object o)
   {
      Map instance = (Map) o;

      //
      HGPersistentHandle[] layout = new HGPersistentHandle[3 * 2];

      String s = (String) instance.get("name");
      // xsd type
      int i = 0;
      HGHandle typeHandle = hg.getTypeSystem().getTypeHandle(
            "http://www.w3.org/2001/XMLSchema#string");
      HGAtomType type = hg.getTypeSystem().getType(
            "http://www.w3.org/2001/XMLSchema#string");
      layout[3 * i] = hg.getPersistentHandle(typeHandle);
      layout[3 * i + 1] = TypeUtils.storeValue(hg, "name", type);
      layout[3 * i + 2] = TypeUtils.storeValue(hg, s, type);

      s = (String) instance.get("city");
      i = 1;
      layout[3 * i] = hg.getPersistentHandle(typeHandle);
      layout[3 * i + 1] = TypeUtils.storeValue(hg, "city", type);
      layout[3 * i + 2] = TypeUtils.storeValue(hg, s, type);

      HGPersistentHandle handle = TypeUtils.getNewHandleFor(hg, instance);
      hg.getStore().store(handle, layout);

      return handle;
   }

   /**
    * 
    */
   public boolean subsumes(
      Object general, Object specific)
   {
      // TODO Auto-generated method stub
      return false;
   }

}
